### ISSUE TITLE
Passing language query parameter not printing PDF in specified language

### ISSUE THREAD

**Issue by malcjackson** [OpenClinica/enketo-express-oc#607] opened 2022-12-14 21:11 UTC
**Describe the bug**
When OpenClinica makes a call to print a PDF casebook and specifies a language using the language parameter, the form prints in English regardless of the specified language.

**To Reproduce**

1. Given a form with a German (de) language
2. Make call to the PDF printing endpoint: https://formprint.openclinica-dev.io/oc/api/v1/instance/view/pdf?lang=de
3. PDF view of form prints
4. Form PDF is in English

**Expected behavior**
Form is in German

**Screenshots**
Endpoint getting called is above, and shown here in logs:
![Screenshot (158)](https://user-images.githubusercontent.com/59966090/207714728-1453ffce-e135-431f-aa39-e3e6a0038397.png)

Example request body:
{
    server_url: "https://technosoft.ngrok.io/OpenClinica/rest2/openrosa/S_REHMANST_650(TEST)";
    form_id: "F_TESTFORM_1-864405cc92ba8e557d8393cba0bdcb2b-query";
    instance_id: "4025f1030585c9312491e725e5dae3a041ae5d0a21df7153a5e4eea11794ba683d60019ec0f151cb";
    return_url: "https://technosoft.ngrok.io/OpenClinica/MainMenu";
    instance: "<data xmlns:oc="http://openclinica.org/xforms" oc:complete="true"   xmlns:enk="http://enketo.org/xforms" > ....";
    ecid: "ded2fa9a538c763bd4dcc2e1710de5646ab48d57741e1d3aaf8f3fbf245ea034";
    instanceAttachments: InstanceAttachments,
}

Is there something on our end required to get the PDF in the specified language?

**Comment by pbowen-oc** [comment] 2022-12-14 23:06
Duplicate of #606

**Closed by pbowen-oc** 2022-12-14 23:06 UTC
