### ISSUE TITLE
Strict constraint not working consistently for radio button/checkboxes

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#168] opened 2019-01-23 19:15 UTC
The attached form's first radio button has a constraint of ". = 1". Whether opened a s anew form or existing record, this constraint works erratically. Once the first radio button is selected, if the user tries to select a different radio button for this item, a strict error alert usually pops up and the value remains unchanged. However, if you do this several times, the value will be cleared and there will be no alert message. In this case, the null value is being saved to the database (we can see in our audit logs and next time we open the form).

[participant xform with constraint on radio button.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/2788786/participant.xform.with.constraint.on.radio.button.xml.txt)

**Comment by MartijnR** [comment] 2019-01-23 20:21
try in `master`

**Comment by MartijnR** [comment] 2019-01-23 22:57
http://localhost:8005/preview/participant/i/?form=http://localhost:3000/form/participant.xform.with.constraint.on.radio.button/form.xml (Centro)

**Comment by MartijnR** [comment] 2019-01-23 23:22
for some reason every 2nd time `this.input.getVal( $input )` is called, it returns `""`, instead of `"2"`.

**Comment by MartijnR** [comment] 2019-01-23 23:44
* [ ] check develop branch

**Comment by MartijnR** [comment] 2019-01-24 00:06
The value is not set the second time. I think the cause could perhaps lie in the unselect functionality for radio buttons.

* [ ] confirm that checkboxes do not have this issue
*

**Comment by MartijnR** [comment] 2019-01-24 23:55
The issue seems to be that the data-checked attribute is not removed when resetting the radio button (due to strict violation).

**Comment by MartijnR** [comment] 2019-01-25 00:19
fixed in 1.72.3.oc-3!

**Comment by MartijnR** [comment] 2019-03-26 16:54
fix not proper

**Closed** 2019-03-26 20:24 UTC
