### ISSUE TITLE
Strict Required fields don't allow closing of form

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#634] opened 2023-02-14 19:48 UTC
**Describe the bug**
Users are experiencing alerts for "strict" required fields while trying to close (not complete) the form. 

![image](https://user-images.githubusercontent.com/87195434/218843715-92846e18-6aae-4446-a0a4-6a5f57892d87.png)

[xform_req_strict.txt](https://github.com/OpenClinica/enketo-express-oc/files/10736262/xform_req_strict.txt)

**Comment by pbowen-oc** [comment] 2023-02-15 05:38
Duplicate of #591

**Closed by pbowen-oc** 2023-02-15 05:38 UTC
