### ISSUE TITLE
RFC view breaks in IE11

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#214] opened 2019-05-20 17:25 UTC
Opening a complete form in edit mode in IE11 is causing the form to load with an Enketo error:
This record is not complete and cannot be used here.
![2019-05-20 13_20_40-Window](https://user-images.githubusercontent.com/25179620/58039926-23115400-7b02-11e9-8662-aa0a46d0d9b7.png)

After this error is cleared, the form has no close button. I think that is an expected behavior for a form which fails to load correctly.

This works without any errors in Chrome.

Here is the endpoint I was loading:
https://form.us.openclinica-dev.io/edit/fs/rfc/c/i/

Here is the error log form IE11:
[IE11 complete form error log.txt](https://github.com/OpenClinica/enketo-express-oc/files/3199039/IE11.complete.form.error.log.txt)

Here is the XForm (extracted from Chrome):
[IE11 Xform.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3199036/IE11.Xform.xml.txt)

Here is the instance that I tried to pull from the call in Chrome:
[instance for IE11 error.txt](https://github.com/OpenClinica/enketo-express-oc/files/3199042/instance.for.IE11.error.txt)

This breaking in both the latest master and the latest develop branches.

**Comment by MartijnR** [comment] 2019-05-20 17:40
Ok, I'm anxiously waiting 20 more IE11-specific issues now... I'm nearly ready to drop support in the rest of Enketo, and cannot even remember when I last opened IE11...

**Comment by pbowen-oc** [comment] 2019-05-20 17:43
Do you recall what that specific error message indicates? Also, am I correct in my recollection that we intentionally do not show the Close button if the form loads improperly?

**Comment by MartijnR** [comment] 2019-05-20 17:49
Yes, the message is shown when there is an attempt to load a record in the rfc view that is not marked as complete (with the `oc:complete="true"` attribute). In this case, it's probably because of some exception that occurs when trying to read this value.

Yes, the Close button is explicitly removed when this error occurs.

**Comment by MartijnR** [comment] 2019-07-26 22:35
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=dn-calculate&instance=\
    <dn-calculate xmlns:oc=\"http://openclinica.org/xforms\" oc:complete=\"true\"><a>1</a><meta><instanceID>a</instanceID></meta></dn-calculate>&instance_id=a&ecid=b" http://localhost:8005/oc/api/v1/instance/edit
```

**Comment by MartijnR** [comment] 2019-07-26 22:56
I think that during merging the record with the default instance the oc: prefix isn't properly added so the XPath query fails.

**Comment by MartijnR** [comment] 2019-08-15 22:34
* [ ] double check for regressions by trying to load record with oc:complete="false" in Chrome
* [ ] in IE11

**Comment by MartijnR** [comment] 2019-08-15 23:21
workaround for IE11 in master `1.77.1.oc-6`

**Closed** 2019-08-21 19:25 UTC
Labels: ready-for-final-review
