### ISSUE TITLE
Error message for items within a repeating group

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#534] opened 2022-03-14 18:03 UTC
**Describe the bug**
Items within a repeating group create an error message during the first time the form is opened. Reference: /single/fs/c/i/

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).
[XForm_3_14.txt](https://github.com/OpenClinica/enketo-express-oc/files/8247466/XForm_3_14.txt)

1. Go to the form
2. Click on the item within a repeating group
3. Enter in a valid value
4. Click the Close or Complete Button
5. Notice the error

**Expected behavior**
Able to enter values into items without receiving the error message. 

**Screenshots**

![Without_Url_Error](https://user-images.githubusercontent.com/87195434/158233532-4642483e-923d-4ef6-9a47-1f3cc58654ba.png)

**Additional context**

**Comment by MartijnR** [comment] 2022-03-15 18:38
* [ ] reproduce in ee-oc
* [ ] reproduce in ee
* [ ]

**Comment by MartijnR** [comment] 2022-03-15 18:57
This is related to the XForm itself. Pyxform produces a `<model>` like this:

```xml
<instance>
				<data id="XForm_3_14" version="1">
					<MHX jr:template="">
						<date_resolved/>
					</MHX>
					<MHX>
						<date_resolved/>
					</MHX>
					<meta>
						<instanceID/>
					</meta>
				</data>
			</instance>
```

and OpenClinica dynamically adds the DN XML nodes (`date_resolved_comment`) as below:

```xml
<instance>
				<data id="XForm_3_14" version="1">
					<MHX jr:template="">
						<date_resolved/>
						<date_resolved_comment oc:queryParent="date_resolved"/>
					</MHX>
					<MHX>
						<date_resolved/>
					</MHX>
					<meta>
						<instanceID/>
					</meta>
				</data>
			</instance>
```

The problem is that the second repeat (`<MHX>`) does not include the added DN node, resulting in a model that is broken.

So this needs to be fixed on the OC side.

**Comment by MartijnR** [comment] 2022-03-15 19:16
@Apotischman @pbowen-oc if this issue also occurs in a currently deployed version, I think it is rather serious.

**Comment by pbowen-oc** [comment] 2022-03-15 22:34
@MartijnR - Thanks for diagnosing this so quickly. Fortunately, this is only a regression in our development branch.

Closing this since it is not an Enketo bug.

**Closed by pbowen-oc** 2022-03-15 22:34 UTC
Labels: on hold or non-enketo
