### ISSUE TITLE
Form can be closed without entering Reason for Change

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#132] opened 2018-10-19 23:25 UTC
Steps:
1. Open a Complete form with the RFC view
2. Change an item value
3. Observe that RFC section appears at the bottom of the page
4. Click the Close button

Expected:
User should be prevented from Closing form since RFC is a required.

Actual:
Form closes without any notification to the user.

**Comment by MartijnR** [comment] 2018-10-22 22:47
Hmm. Should have been fixed with #119. (And I cannot reproduce)

What is the version on the Enketo home page? I see `version: 1.72.2-592-g27c6edc`.

**Comment by MartijnR** [comment] 2018-10-24 19:39
check if event is triggered to parentWindow

**Comment by MartijnR** [comment] 2018-10-26 20:07
@pbowen-oc None of the oc servers I have been using seem accessible. Could you share an OC dev server login url please?

**Comment by pbowen-oc** [comment] 2018-10-26 23:17
@MartijnR - I just sent you an invitation.

**Comment by MartijnR** [comment] 2018-10-30 23:05
https://form.dev.openclinica.io/edit/fs/rfc/c/i/::994103....bc9?ecid=0c226d66.673d&PID=006&instance_id=c3c&parentWindowOrigin=https%3A%2F%2Fcust1.dev.openclinica.io&returnUrl=https%3A%2F%2Fcust1.dev.openclinica.io%2FOpenClinica%2FMainMenu&jini=false

**Comment by MartijnR** [comment] 2018-11-02 19:10
* [ ] add warning if attempt to load incomplete record

**Closed** 2018-11-05 23:05 UTC

**Comment by MartijnR** [comment] 2018-11-07 19:47
New way to pass completeness state is described here: https://github.com/OpenClinica/enketo-express-oc/issues/50#issuecomment-420037360
