### ISSUE TITLE
Add Strict Constraint and Strict Required support to form views

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#170] opened 2019-01-30 03:26 UTC
Add strict constraint and strict required to our normal form views. Unlike what we did for the Participate view, the normal views will allow a mix of strict and non-strict constraints and requireds on the form (a single item could have strict required and non-strict constraint or vice-versa). Also unlike the Participate view, relevant errors will remain non-strict.

In the normal views, strict errors cannot be suppressed by adding queries. Strict errors should prevent the user from using the Close or Complete buttons (the user would not be prompted to add autoqueries while there is a strict error).

Strict errors should display with the orange color used in the Participate view and should have the same popup windows as in the Participate view when they are triggered.

**Comment by MartijnR** [comment] 2019-02-05 16:42
Is there any webform view that will not have strict constraints and strict requireds?

**Comment by MartijnR** [comment] 2019-02-05 16:46
* [ ] figure out how relevant errors are dealt with in Participate views
* [ ] change relevant error behavior only in Participate views
* [ ] query behavior (isn't this done in form definition?)
* [ ] CLose/Complete button behavior (different from Participate?)

**Comment by MartijnR** [comment] 2019-02-05 16:49
> a single item could have strict required and non-strict constraint or vice-versa

This is huge. Need to think abt this first. I won't be able to work on such a complex and large custom project for a while for sure.

**Comment by MartijnR** [comment] 2019-02-05 18:00
Thanks. Is there a combination of strict required and non-strict required possible in a question? (and same question for constraint)

**Comment by pbowen-oc** [comment] 2019-02-05 19:52
For now we only support one required and one constraint per item. We don't plan to support multiple required expressions per item, but we do plan to support multiple constraints per item later this year. In the future when we support multiple constraints per item, then we would need to support one constrain as strict and another constraint as non-strict for the same item.

**Comment by MartijnR** [comment] 2019-02-08 01:51
@pbowen-oc this is ready for testing (in `master`). I had to substantially rewrite most of the various Close and Complete button logics, and I may have caused some regressions.

**Comment by pbowen-oc** [comment] 2019-03-29 16:28
@MartijnR  - After discussing this further internally, we want a strict error to prevent the user from using the Complete button as mentioned above. However, we want to allow the user to use the Close button even if there is a strict error (unless the form is already marked Complete (I think)). In that case the user should be prompted about fixing the error before the form is closed (as they are for non-strict errors) and an autoquery should be added to the item with a strict error if they decide to proceed with closing the form (as happens for items with non-strict errors). Ideally, that autoquery would only be added if the item does not already have a New or Updated query. Based on the logic we include on the form, the autoquery will not suppress the strict error message when then the user next comes into the form.

Strict errors should continue to prevent navigating forward in the form.

Related, but for Participate specifically - We'd like to allow Participate users to close forms even if they have strict errors. Can we add an autoquery in that case even though the Participate XForm does not include query items? Is there a workaround we could use specifically for the Participate form view to allow this without needing to add the query item to that XForm?

**Comment by MartijnR** [comment] 2019-03-29 21:17
Can't you make these requirements more complex...? :sweat:

**Comment by MartijnR** [comment] 2019-03-29 21:28
* [ ]  figure out if which of the 4 different close functions need updates wrt: modal for strict + autoqueries
* [ ] autoqueries only added if not new or updated query (or is this already the case?)
* [ ] check Close behavior if record was marked as complete

**Comment by MartijnR** [comment] 2019-03-29 21:43
Notes to self:

* there is no consideration of strict vs. non-strict in the various close functions. They are treated the same.

**Comment by MartijnR** [comment] 2019-03-29 21:57
@pbowen-oc currently the regular close function only looks at **constraint** strict/non-strict violations (not required violations) in order to show a modal and optionally add autoqueries. Does this need to change?

**Comment by pbowen-oc** [comment] 2019-04-03 22:57
@MartijnR - We discussed this internally and have clarified the requirements as follows:

For Participant form view, there is no change to Close functionality. Strict errors should continue to prevent the user from closing the form.

For other editable form views, let the user use the Close button even if there are strict errors. 
- If there is a strict constraint error, add an autoquery for the item (regardless of whether the form was opened as complete or not complete). 
- If there is a strict required error and the form was opened as not complete, do not add an autoquery for the item. 
- If there is a strict required error and the form was opened as complete, add an autoquery for the item. 

If there is a strict error of any kind and the form was opened as not complete, do not let the user use the Complete button.

For read-only and review-only views, let the user use the Close button regardless of strict errors.

**Comment by MartijnR** [comment] 2019-04-08 17:27
@pbowen-oc, would you like this in master or in a separate branch? It's quite likely to have some issues initially.

**Comment by MartijnR** [comment] 2019-04-08 17:32
@powen-oc, wrt closing a record that what previously marked as complete: currently autoqueries are added for **all** required and constraint violations. Should that change to only do this for strict violations?

**Comment by pbowen-oc** [comment] 2019-04-08 19:15
@MartijnR - We're locking down our current release now, so please put this in a separate branch for now.

For records opened that were previously marked complete, autoqueries should continue to be added for any non-strict error when the user closes the form (and now the autoqueries should also be added for strict errors as well).

**Comment by MartijnR** [comment] 2019-04-08 20:08
* [ ] test autoquery generation after refactor

**Comment by MartijnR** [comment] 2019-04-08 22:37
ready for initial integration testing

**Comment by pbowen-oc** [comment] 2019-04-22 16:08
When I have a strict constraint firing and I try to Close the form (incomplete form), it prompts me about adding an auto-query as expected. When I click Proceed it seems to add the autoquery, but then it won't let me out of the form. This same window just stays there on the screen.

![2019-04-22 12_02_38-Window](https://user-images.githubusercontent.com/25179620/56510148-f82de300-64f6-11e9-91d2-ae91f8f209da.png)

**Comment by MartijnR** [comment] 2019-04-22 16:38
Will check. Just to be sure, this in the `develop branch`, right?

**Comment by pbowen-oc** [comment] 2019-04-22 16:44
Yes, this is from the develop branch.

**Comment by MartijnR** [comment] 2019-04-23 20:20
I don't experience this problem, using an old version of that form, with the same constraint error. There was an intermediate state that had this problem. I am wondering if you are using an older version.

**Comment by MartijnR** [comment] 2019-04-23 20:21
P.S. I tested with an empty form in a URL like this: http://localhost:8005/single/fs/i/::8FaWL0oC. You might be using a different view.

**Comment by pbowen-oc** [comment] 2019-04-24 00:04
I'm still observing this and as far as I know we have deployed the develop branch. My URL for a new form is like /single/fs/c/i/::380aac99091419ebf0ff63c6fd4497a0

**Comment by pbowen-oc** [comment] 2019-04-24 17:50
We checked on this and we did deploy the latest develop branch code. Is there anything else I can do to verify this?

**Comment by MartijnR** [comment] 2019-04-24 19:40
Thanks. I can reproduce with your form. http://localhost:8005/single/fs/i/::J4Y4Zcse?ecid=1

**Comment by MartijnR** [comment] 2019-04-24 19:45
`data-constraint="((. >= 90 and . <= 105 and  /demo-vitals-grid-v22-strict/page1/temp_group/temp_units  = 2) or (. >= 32 and . <= 41 and  /demo-vitals-grid-v22-strict/page1/temp_group/temp_units  = 1) or  /demo-vitals-grid-v22-strict/page1/temp_group/temp_units  = '') and (. = round(.,1))"`

**Comment by MartijnR** [comment] 2019-04-24 19:46
@pbowen-oc, the constraint is missing the comment-status() clause so the autoquery does not make it valid.

**Comment by pbowen-oc** [comment] 2019-04-24 20:11
@MartijnR - Yes, that is the intent. This is a strict check, so we want to add the autoquery to identify a data issue for our data managers, but the query will not suppress the error message and make the value valid. This goes along with the requirement above:

- If there is a strict constraint error, add an autoquery for the item if it does not already have a new or updated query (regardless of whether the form was opened as complete or not complete). Prompt the user before adding the autoquery.

One the item has a new or updated query, this autoquery action is complete and no longer needed.

**Comment by MartijnR** [comment] 2019-04-24 21:38
Ok, thanks. Sorry, I never understood that requirement it seems... I think it may work as desired now (at least in some views), though the fix was suspiciously easy.

**Comment by pbowen-oc** [comment] 2019-04-25 17:45
It looks like that issue is resolved now in edit mode. I click Proceed, the autoquery is added, and the form closes as expected.  However, I see a different issue now that issue is resolved.

When an item has a strict error message showing and it already has a new or updated query, Closing the form should not prompt about adding an autoquery to that item. The form should simply be able to close in this case.

When I have this on my form (strict constraint firing an item already has a new query):
![2019-04-25 13_37_46-OpenClinica](https://user-images.githubusercontent.com/25179620/56756593-177b7900-6760-11e9-8bc4-a615ce13536b.png)

I'm getting this when I click Close:
![2019-04-25 13_38_02-OpenClinica](https://user-images.githubusercontent.com/25179620/56756657-3d088280-6760-11e9-89e5-a216a409ded3.png)

When I click Proceed the form closes without adding a new autoquery to this item. The expected behavior is that this window does not appear at all, no autoquery is added, and the form closes.

**Comment by MartijnR** [comment] 2019-04-25 20:25
Hmm. That's tricky. I can do a search for a query icon color/status but that feels a bit fragile.

**Comment by pbowen-oc** [comment] 2019-04-25 20:47
Isn't it already doing something like that to determine whether to actually add the autoquery or not?

**Comment by MartijnR** [comment] 2019-04-25 21:09
yes, but we cannot really use that mechanism. It simply sends an event to each invalid dn widget without checking its status.

The widget then adds an autoquery if it is not "new" or "updated".

But I'll figure something out.

**Comment by MartijnR** [comment] 2019-04-29 20:39
@pbowen-oc, I think using the icon is the way to go. However, I believe that currently the regular close button for a not-completed-record looks at all constraint violations and doesn't care about whether they are strict or not. 

1. Is it correct that it should keep doing that but ignore those that have a new or updated query?
2. Should Close in Participant view also ignore those errors that have a new or updated query?

**Comment by pbowen-oc** [comment] 2019-04-29 20:54
@MartijnR - 
1. Yes. Non-strict errors that have a new or updated query will never have a constraint violation since we put the query status into the constraint logic and new/updated query status satisfies the constraint.
2. We never include queries in Participant view, so this is not a relevant scenario.

**Comment by MartijnR** [comment] 2019-04-29 20:55
Got it. Thanks!

**Comment by pbowen-oc** [comment] 2019-04-30 23:32
I'm seeing the same behavior as in https://github.com/OpenClinica/enketo-express-oc/issues/170#issuecomment-486771396 when I opened an already completed form and try to close while there is a strict constraint or required firing. The autoquery seems to be added to the constraint/required as expected, but it is not letting me out of the form.

I'm opening this record with view /edit/fs/rfc/c/i/.

[strict xform test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/3133473/strict.xform.test.xml.txt)

**Comment by MartijnR** [comment] 2019-05-01 21:50
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=vitals15&ecid=a&instance=<demo-vitals-grid-v15 xmlns:oc=\"http://openclinica.org/xforms\" oc:complete=\"true\"><page1/></demo-vitals-grid-v15>&instance_id=a" http://localhost:8005/oc/api/v1/instance/edit/rfc/c
```

**Comment by MartijnR** [comment] 2019-05-01 22:15
Bypassing any errors in the Complete function is violating quite a lot of the existing checks.

When the Close button is clicked for a completed form, it essentially has to pass all the checks that a Complete button click has, and it calls the /complete fieldsubmission API endpoint.

So now have conceptually two different acceptable records to send to the /complete endpoint. One that has to be absolutely valid and one that may be invalid as long as those invalid questions have a new or updated query.

Or can we say across the board that invalid (strict and non-strict) records are always acceptable for Close/Complete as long as those invalid questions have a new or updated query?

**Comment by pbowen-oc** [comment] 2019-05-01 23:24
We want to keep it so that to mark a form complete (i.e., change it from incomplete to complete), it has to be a valid record (no errors). If it's not a valid record, the user can come back another time and update the data as needed to make it a valid record and then mark it complete. If we allowed allowed strict errors to be bypassed when changing a form to complete, then those strict errors wouldn't mean what we want them to mean.

However, when considering simply closing the form without changing its status (leaving as incomplete or leaving as complete), we want to be more forgiving since we don't want users to get stuck in the form when they may not be able to resolve the errors they see (which would eventually just result in them closing the browser tab to get out). We don't want users to get stuck and close the tab since that's not user friendly and it does not allow us to add autoqueries in a consistent manner (our general model is that data is either valid or a query has been logged for it and therefore it will go through the data management cycle, although incomplete records are more forgiving since users will come back to complete the data entry later). Due to our autosave model, data has already been saved at the time an error message is shown, so we need to give the user a reasonable way out of the form or they will make up their own and reduce the quality of the data/queries entered.

So, if a form is not yet complete, we want Close to be permitted and have it add autoqueries appropriate for an incomplete record (i.e., just for constraints, not for required or relevant which are less important when data entry is still in progress). If a form is opened as already complete, then we want the user to be able to Close it and have autoqueries added to all firing errors (including constraint, required, and relevant).

For strict constraint and strict required errors and relevant errors, they will never be suppressed by adding a query (we don't want the error message to disappear), so we need to look at whether they have new/updated query status. For non-strict constraint and non-strict required errors, in non-participate views a new, updated, or closed query will always suppress the error due to the logic we include in the form (in participate views, we always treat constraints and required errors as strict and queries are part of the form).

So, the desired logic surrounding complete records does seem to have two distinct scenarios.

Note: In thinking this through, I noticed that we don't currently let users close a Complete record if it has a relevant error.  As mentioned above, I think that should be changed to allow the user to close the already complete record if there is a new/updated query on items with relevant errors. That seems to be out of scope for the current ticket, but I wanted to mention it so it could be considered holistically.

**Comment by MartijnR** [comment] 2019-05-02 16:59
Ok, I'll add that relevant error bypass option for already completed records. The remaining difference will be that relevant errors never get autoqueries.

**Comment by MartijnR** [comment] 2019-05-02 17:26
Ok, another step closer. Ready for verification in `develop`.

**Comment by pbowen-oc** [comment] 2019-05-22 00:26
@MartijnR - I'm seeing he expected behavior for not yet complete records.

However, for already completed records, if I have a strict constraint/required error firing and the item associated with that already has a new or updated query, when I click the Close button I expect it to simply close the form and not add an autoquery. However, it is showing me the alert that some fields have errors and autoqueries are needed. If I click Proceed, it is exiting without adding an additional autoquery to that item (good). Note: If the item didn't already have a new/updated query, I'd want the alert to appear and I'd want to Proceed to add an autoquery (and it seems to be doing that now as expected).

So, the remaining issue is that the current behavior is unexpectedly showing me the alert for an item with a strict constraint/required error that already has a new/updated query when I Close an already completed form even though it is not going to add another query to that item.

**Comment by MartijnR** [comment] 2019-06-07 23:01
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=170&ecid=a&instance=<demo-vitals-grid-v22-strict xmlns:oc=\"http://openclinica.org/xforms\" oc:comlete=\"true\"><page1/></demo-vitals-grid-v22-strict>&instance_id=a" http://localhost:8005/oc/api/v1/instance/edit/rfc/c
```

**Comment by MartijnR** [comment] 2019-06-07 23:18
As far as I understand there is **no consideration whatsoever** wrt strict or non-strict violations to close a completed record. They both get autoqueries. The difference is that an autoquery for a strict item won't resolve the violation (constraint/required) due to the form logic.

 If that is correct, then I think the issue is fixed in develop. Otherwise, it's back to the drawing board!

**Comment by pbowen-oc** [comment] 2019-06-07 23:59
I won't be able to test this until next week. 

In the meantime, I think there is a difference between strict and non-strict errors when closing a complete record but it may not matter on your end. Both types of errors should get an autoquery on Close if and only if there isn't currently a New or Updated query on that item. For non-strict, our particular usage means that there will never be an error while there is a New or Updated Query, so this scenario shouldn't matter at all. For strict however, the item may be showing the error message and already have a New or Updated query and in that case we don't want to get into the workflow for adding an autoquery to it.

**Comment by pbowen-oc** [comment] 2019-06-12 00:59
Just an FYI, this appears to be working to spec now :)

I plan to demo it to tomorrow and I'll let you know if we need any changes after that. I think we will definitely need some minor UI updates and possibly something around relevant errors in complete forms. I will log separate issues for any changes needed for those.

**Comment by MartijnR** [comment] 2019-06-12 15:00
Great. There is some issue in master wrt relevant which is fixed in the multiple-query branch. So would be good to merge those branches once it becomes workable on a dev server (even if full multi-query supported has not been added to backend).

**Closed** 2019-06-12 15:00 UTC
