### ISSUE TITLE
textContent null error (multipage, edit)

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#109] opened 2018-09-17 16:14 UTC
> Opening a multi-page form that contains an existing record is causing an error to be displayed - "TypeError: Cannot read property "textContext" of null"

**Comment by MartijnR** [comment] 2018-09-17 19:33
Cannot reproduce. Will add some temporary logging to get the exact record that is being loaded for an XForm that can reproduce it.

**Comment by pbowen-oc** [comment] 2018-09-17 22:35
This is happening with my usual test form.

**Comment by MartijnR** [comment] 2018-09-18 17:40
Need to get the exact instance that OC is providing (and is temporarily logged to console). So let's get this in the meeting.

**Comment by pbowen-oc** [comment] 2018-09-18 19:19
loading record: <demo-vitals-grid-v15 xmlns:oc="http://openclinica.org/xforms"  xmlns:enk="http://enketo.org/xforms" ><page1><rndm>4</rndm><cohort>D</cohort><temp_yn></temp_yn><temp_group><temp></temp><temp_units></temp_units><temp_unit_des></temp_unit_des><temp_entry></temp_entry><temp_entry_hidden></temp_entry_hidden><temp_units_comment></temp_units_comment><temp_unit_des_comment></temp_unit_des_comment><temp_entry_hidden_comment></temp_entry_hidden_comment><temp_comment></temp_comment><temp_entry_comment></temp_entry_comment></temp_group><wh_y></wh_y><wh_units></wh_units><weight></weight><weight_unit_des>weight not entered</weight_unit_des><height></height><height_unit_des>height not entered</height_unit_des><bmi></bmi><bmi_hidden></bmi_hidden><bmi_calc>0</bmi_calc><bmi_rad></bmi_rad><resp_rate></resp_rate><pulse></pulse><dob></dob><age></age><ext_eventdate></ext_eventdate><ext_username></ext_username><ext_userrole></ext_userrole><url_item>https://openclinica.com</url_item><format1></format1><format2></format2><fo…3_comment><ext_username_comment></ext_username_comment><url_item_comment>{"queries":[],"logs":[{"type":"audit","message":"Value changed from \"\" to \"https://openclinica.com\"","user":"pbowenadm","assigned_to":"pbowenadm","date_time":"2018-09-18 19:17:27.080 Z"}]}</url_item_comment><wh_units_comment></wh_units_comment><format4_comment></format4_comment><pulse_comment></pulse_comment><cohort_comment></cohort_comment><age_comment></age_comment><resp_rate_comment></resp_rate_comment><ext_userrole_comment></ext_userrole_comment><weight_comment></weight_comment><height_comment></height_comment><format1_comment></format1_comment><wh_y_comment></wh_y_comment><bmi_comment></bmi_comment><weight_unit_des_comment></weight_unit_des_comment><bmi_calc_comment></bmi_calc_comment><bmi_rad_comment></bmi_rad_comment></page1><page2><bp_yn></bp_yn><bp_rg enk:last-used-ordinal="1"  enk:ordinal="1" ><bp_rg_num_init></bp_rg_num_init><bp_rg_num></bp_rg_num><bp_row></bp_row><bp_pos></bp_pos><bp_sys></bp_sys><bp_sys_val></bp_sys_val><bp_sys_count></bp_sys_count><bp_dia></bp_dia><bp_dia_val></bp_dia_val><bp_dia_count></bp_dia_count><bp_ratio></bp_ratio><bp_ratio_hidden></bp_ratio_hidden><bp_dt_prec></bp_dt_prec><bp_dt_ymd></bp_dt_ymd><bp_dt_ym></bp_dt_ym><bp_dt_y></bp_dt_y><bp_dia_count_comment></bp_dia_count_comment><bp_row_comment></bp_row_comment><bp_dt_ym_comment></bp_dt_ym_comment><bp_dt_prec_comment></bp_dt_prec_comment><bp_sys_comment></bp_sys_comment><bp_ratio_hidden_comment></bp_ratio_hidden_comment><bp_sys_val_comment></bp_sys_val_comment><bp_dt_y_comment></bp_dt_y_comment><bp_rg_num_comment></bp_rg_num_comment><bp_rg_num_init_comment></bp_rg_num_init_comment><bp_pos_comment></bp_pos_comment><bp_dia_val_comment></bp_dia_val_comment><bp_ratio_comment></bp_ratio_comment><bp_sys_count_comment></bp_sys_count_comment><bp_dt_ymd_comment></bp_dt_ymd_comment><bp_dia_comment></bp_dia_comment></bp_rg><bp_sys_mean></bp_sys_mean><bp_dia_mean></bp_dia_mean><bp_number></bp_number><bp_ratio_lookup></bp_ratio_lookup><likert_group><systolic_agreement></systolic_agreement><diastolic_agreement></diastolic_agreement><diastolic_agreement_comment></diastolic_agreement_comment><systolic_agreement_comment></systolic_agreement_comment></likert_group><newselectitem></newselectitem><newdecimal></newdecimal><pain_level></pain_level><vas_question></vas_question><media_yn></media_yn><pic></pic><sound></sound><vid></vid><afile_doc></afile_doc><afile_any></afile_any><pic_ann></pic_ann><pic_draw></pic_draw><pic_sig></pic_sig><ecg_picture></ecg_picture><cascade1></cascade1><cascade2></cascade2><cascade3></cascade3><us_map></us_map><add_notes></add_notes><pic_comment></pic_comment><bp_number_comment></bp_number_comment><bp_yn_comment></bp_yn_comment><cascade1_comment></cascade1_comment><bp_sys_mean_comment></bp_sys_mean_comment><pic_ann_comment></pic_ann_comment><media_yn_comment></media_yn_comment><newdecimal_comment></newdecimal_comment><pain_level_comment></pain_level_comment><pic_sig_comment></pic_sig_comment><vid_comment></vid_comment><afile_doc_comment></afile_doc_comment><bp_ratio_lookup_comment></bp_ratio_lookup_comment><sound_comment></sound_comment><us_map_comment></us_map_comment><add_notes_comment></add_notes_comment><newselectitem_comment></newselectitem_comment><bp_dia_mean_comment></bp_dia_mean_comment><cascade3_comment></cascade3_comment><ecg_picture_comment></ecg_picture_comment><afile_any_comment></afile_any_comment><pic_draw_comment></pic_draw_comment><cascade2_comment></cascade2_comment><vas_question_comment></vas_question_comment></page2><meta><instanceID>uuid:1234</instanceID><instanceID_comment></instanceID_comment></meta></demo-vitals-grid-v15>

**Comment by MartijnR** [comment] 2018-09-18 20:04
Had to make some corrections (format3_comment was cut off), and could not reproduce it.

It likely has something to do with the clinicaldata calculations (which I had disabled in order to load the form). @pbowen-oc, do you have the clinicaldata.xml file that is used with that form?

**Comment by pbowen-oc** [comment] 2018-09-18 22:27
@MartijnR - I reproduced it with an older version of that form that does not read external data:

record: <demo-vitals-grid-v6 xmlns:oc="http://openclinica.org/xforms"  xmlns:enk="http://enketo.org/xforms" ><page1><rndm>1</rndm><cohort>A</cohort><temp_yn></temp_yn><temp_group><temp></temp><temp_units></temp_units><temp_unit_des></temp_unit_des><temp_entry></temp_entry><temp_entry_hidden></temp_entry_hidden><temp_units_comment></temp_units_comment><temp_unit_des_comment></temp_unit_des_comment><temp_entry_hidden_comment></temp_entry_hidden_comment><temp_comment></temp_comment><temp_entry_comment></temp_entry_comment></temp_group><wh_y></wh_y><wh_units></wh_units><weight></weight><weight_unit_des>weight not entered</weight_unit_des><height></height><height_unit_des>height not entered</height_unit_des><bmi></bmi><bmi_hidden></bmi_hidden><bmi_calc>0</bmi_calc><bmi_rad></bmi_rad><resp_rate></resp_rate><pulse></pulse><format1></format1><format2></format2><format3></format3><format4></format4><bmi_hidden_comment></bmi_hidden_comment><format2_comment></format2_comment><height_unit_des_comment></height_unit_des_comment><temp_yn_comment></temp_yn_comment><rndm_comment></rndm_comment><format3_comment></format3_comment><wh_units_comment></wh_units_comment><format4_comment></format4_comment><pulse_comment></pulse_comment><cohort_comment></cohort_comment><resp_rate_comment></resp_rate_comment><weight_comment></weight_comment><height_comment></height_comment><format1_comment></format1_comment><wh_y_comment></wh_y_comment><bmi_comment></bmi_comment><weight_unit_des_comment></weight_unit_des_comment><bmi_calc_comment></bmi_calc_comment><bmi_rad_comment></bmi_rad_comment></page1><page2><bp_yn></bp_yn><bp_rg enk:last-used-ordinal="1"  enk:ordinal="1" ><bp_rg_num_init></bp_rg_num_init><bp_rg_num></bp_rg_num><bp_row></bp_row><bp_pos></bp_pos><bp_sys></bp_sys><bp_sys_val></bp_sys_val><bp_sys_count></bp_sys_count><bp_dia></bp_dia><bp_dia_val></bp_dia_val><bp_dia_count></bp_dia_count><bp_ratio></bp_ratio><bp_ratio_hidden></bp_ratio_hidden><bp_dt_prec></bp_dt_prec><bp_dt_ymd></bp_dt_ymd><bp_dt_ym></bp_dt_ym><bp_dt_y></bp_dt_y><bp_dia_count_comment></bp_dia_count_comment><bp_row_comment></bp_row_comment><bp_dt_ym_comment></bp_dt_ym_comment><bp_dt_prec_comment></bp_dt_prec_comment><bp_sys_comment></bp_sys_comment><bp_ratio_hidden_comment></bp_ratio_hidden_comment><bp_sys_val_comment></bp_sys_val_comment><bp_dt_y_comment></bp_dt_y_comment><bp_rg_num_comment></bp_rg_num_comment><bp_rg_num_init_comment></bp_rg_num_init_comment><bp_pos_comment></bp_pos_comment><bp_dia_val_comment></bp_dia_val_comment><bp_ratio_comment></bp_ratio_comment><bp_sys_count_comment></bp_sys_count_comment><bp_dt_ymd_comment></bp_dt_ymd_comment><bp_dia_comment></bp_dia_comment></bp_rg><bp_sys_mean></bp_sys_mean><bp_dia_mean></bp_dia_mean><bp_number></bp_number><bp_ratio_lookup></bp_ratio_lookup><likert_group><systolic_agreement></systolic_agreement><diastolic_agreement></diastolic_agreement><diastolic_agreement_comment></diastolic_agreement_comment><systolic_agreement_comment></systolic_agreement_comment></likert_group><newselectitem></newselectitem><newdecimal></newdecimal><pain_level></pain_level><vas_question></vas_question><media_yn></media_yn><pic></pic><ecg_picture></ecg_picture><cascade1></cascade1><cascade2></cascade2><cascade3></cascade3><us_map></us_map><add_notes></add_notes><pic_comment></pic_comment><bp_number_comment></bp_number_comment><bp_yn_comment></bp_yn_comment><cascade1_comment></cascade1_comment><bp_sys_mean_comment></bp_sys_mean_comment><media_yn_comment></media_yn_comment><newdecimal_comment></newdecimal_comment><pain_level_comment></pain_level_comment><bp_ratio_lookup_comment></bp_ratio_lookup_comment><us_map_comment></us_map_comment><add_notes_comment></add_notes_comment><newselectitem_comment></newselectitem_comment><bp_dia_mean_comment></bp_dia_mean_comment><cascade3_comment></cascade3_comment><ecg_picture_comment></ecg_picture_comment><cascade2_comment></cascade2_comment><vas_question_comment></vas_question_comment></page2><meta><instanceID>uuid:1234</instanceID><instanceID_comment></instanceID_comment></meta></demo-vitals-grid-v6>

**Comment by pbowen-oc** [comment] 2018-09-18 22:31
@MartijnR - Here is the XForm for that last form (zipped since it won't let me upload an XML file). I'm just opening it, letting the calculations process and submit, closing it, and then reopening it to see the error message.
[TypeError - new.zip](https://github.com/OpenClinica/enketo-express-oc/files/2394726/TypeError.-.new.zip)

**Comment by pbowen-oc** [comment] 2018-09-18 22:42
@MartijnR - I have found the condition that triggers this. If I open the form the first time, select Yes for the BP question on page 2 and add a repeat (so there are 2 total), then I can reopen the form without error. If I don't add the 2nd repeat, then the error occurs.  So, here is what the Console log outputs when I open that record successfully:

record: <demo-vitals-grid-v6 xmlns:oc="http://openclinica.org/xforms"  xmlns:enk="http://enketo.org/xforms" ><page1><rndm>4</rndm><cohort>D</cohort><temp_yn></temp_yn><temp_group><temp></temp><temp_units></temp_units><temp_unit_des></temp_unit_des><temp_entry></temp_entry><temp_entry_hidden></temp_entry_hidden><temp_units_comment></temp_units_comment><temp_unit_des_comment></temp_unit_des_comment><temp_entry_hidden_comment></temp_entry_hidden_comment><temp_comment></temp_comment><temp_entry_comment></temp_entry_comment></temp_group><wh_y></wh_y><wh_units></wh_units><weight></weight><weight_unit_des>weight not entered</weight_unit_des><height></height><height_unit_des>height not entered</height_unit_des><bmi></bmi><bmi_hidden></bmi_hidden><bmi_calc>0</bmi_calc><bmi_rad></bmi_rad><resp_rate></resp_rate><pulse></pulse><format1></format1><format2></format2><format3></format3><format4></format4><bmi_hidden_comment></bmi_hidden_comment><format2_comment></format2_comment><height_unit_des_comment></height_unit_des_comment><temp_yn_comment></temp_yn_comment><rndm_comment></rndm_comment><format3_comment></format3_comment><wh_units_comment></wh_units_comment><format4_comment></format4_comment><pulse_comment></pulse_comment><cohort_comment></cohort_comment><resp_rate_comment></resp_rate_comment><weight_comment></weight_comment><height_comment></height_comment><format1_comment></format1_comment><wh_y_comment></wh_y_comment><bmi_comment></bmi_comment><weight_unit_des_comment></weight_unit_des_comment><bmi_calc_comment></bmi_calc_comment><bmi_rad_comment></bmi_rad_comment></page1><page2><bp_yn>1</bp_yn><bp_rg enk:last-used-ordinal="2"  enk:ordinal="1" ><bp_rg_num_init>1</bp_rg_num_init><bp_rg_num>1</bp_rg_num><bp_row>1</bp_row><bp_pos>Standing</bp_pos><bp_sys></bp_sys><bp_sys_val>0</bp_sys_val><bp_sys_count>0</bp_sys_count><bp_dia></bp_dia><bp_dia_val>0</bp_dia_val><bp_dia_count>0</bp_dia_count><bp_ratio>0</bp_ratio><bp_ratio_hidden></bp_ratio_hidden><bp_dt_prec></bp_dt_prec><bp_dt_ymd></bp_dt_ymd><bp_dt_ym></bp_dt_ym><bp_dt_y></bp_dt_y><bp_dia_count_comment></bp_dia_count_comment><bp_row_comment>{"queries":[],"logs":[{"type":"audit","message":"Value changed from \"\" to \"1\"","user":"pbowenadm","assigned_to":"pbowenadm","date_time":"2018-09-18 22:40:52.180 Z"}]}</bp_row_comment><bp_dt_ym_comment></bp_dt_ym_comment><bp_dt_prec_comment></bp_dt_prec_comment><bp_sys_comment></bp_sys_comment><bp_ratio_hidden_comment></bp_ratio_hidden_comment><bp_sys_val_comment></bp_sys_val_comment><bp_dt_y_comment></bp_dt_y_comment><bp_rg_num_comment></bp_rg_num_comment><bp_rg_num_init_comment></bp_rg_num_init_comment><bp_pos_comment>{"queries":[],"logs":[{"type":"audit","message":"Value changed from \"\" to \"Standing\"","user":"pbowenadm","assigned_to":"pbowenadm","date_time":"2018-09-18 22:40:52.333 Z"}]}</bp_pos_comment><bp_dia_val_comment></bp_dia_val_comment><bp_ratio_comment>{"queries":[],"logs":[{"type":"audit","message":"Value changed from \"\" to \"0\"","user":"pbowenadm","assigned_to":"pbowenadm","date_time":"2018-09-18 22:40:52.481 Z"}]}</bp_ratio_comment><bp_sys_count_comment></bp_sys_count_comment><bp_dt_ymd_comment></bp_dt_ymd_comment><bp_dia_comment></bp_dia_comment></bp_rg><bp_rg   enk:ordinal="2" ><bp_rg_num_init>1</bp_rg_num_init><bp_rg_num>1</bp_rg_num><bp_row>2</bp_row><bp_pos>Sitting</bp_pos><bp_sys></bp_sys><bp_sys_val>0</bp_sys_val><bp_sys_count>0</bp_sys_count><bp_dia></bp_dia><bp_dia_val>0</bp_dia_val><bp_dia_count>0</bp_dia_count><bp_ratio>0</bp_ratio><bp_ratio_hidden></bp_ratio_hidden><bp_dt_prec></bp_dt_prec><bp_dt_ymd></bp_dt_ymd><bp_dt_ym></bp_dt_ym><bp_dt_y></bp_dt_y><bp_dia_count_comment></bp_dia_count_comment><bp_row_comment>{"queries":[],"logs":[{"type":"audit","message":"Value changed from \"\" to \"2\"","user":"pbowenadm","assigned_to":"pbowenadm","date_time":"2018-09-18 22:40:53.398 Z"}]}</bp_row_comment><bp_dt_ym_comment></bp_dt_ym_comment><bp_dt_prec_comment></bp_dt_prec_comment><bp_sys_comment></bp_sys_comment><bp_ratio_hidden_comment></bp_ratio_hidden_comment><bp_sys_val_comment></bp_sys_val_comment><bp_dt_y_comment></bp_dt_y_comment><bp_rg_num_comment></bp_rg_num_comment><bp_rg_num_init_comment></bp_rg_num_init_comment><bp_pos_comment>{"queries":[],"logs":[{"type":"audit","message":"Value changed from \"\" to \"Sitting\"","user":"pbowenadm","assigned_to":"pbowenadm","date_time":"2018-09-18 22:40:53.543 Z"}]}</bp_pos_comment><bp_dia_val_comment></bp_dia_val_comment><bp_ratio_comment>{"queries":[],"logs":[{"type":"audit","message":"Value changed from \"\" to \"0\"","user":"pbowenadm","assigned_to":"pbowenadm","date_time":"2018-09-18 22:40:53.715 Z"}]}</bp_ratio_comment><bp_sys_count_comment></bp_sys_count_comment><bp_dt_ymd_comment></bp_dt_ymd_comment><bp_dia_comment></bp_dia_comment></bp_rg><bp_sys_mean></bp_sys_mean><bp_dia_mean></bp_dia_mean><bp_number></bp_number><bp_ratio_lookup></bp_ratio_lookup><likert_group><systolic_agreement></systolic_agreement><diastolic_agreement></diastolic_agreement><diastolic_agreement_comment></diastolic_agreement_comment><systolic_agreement_comment></systolic_agreement_comment></likert_group><newselectitem></newselectitem><newdecimal></newdecimal><pain_level></pain_level><vas_question></vas_question><media_yn></media_yn><pic></pic><ecg_picture></ecg_picture><cascade1></cascade1><cascade2></cascade2><cascade3></cascade3><us_map></us_map><add_notes></add_notes><pic_comment></pic_comment><bp_number_comment></bp_number_comment><bp_yn_comment>{"queries":[],"logs":[{"type":"audit","message":"Value changed from \"\" to \"1\"","user":"pbowenadm","assigned_to":"pbowenadm","date_time":"2018-09-18 22:40:52.029 Z"}]}</bp_yn_comment><cascade1_comment></cascade1_comment><bp_sys_mean_comment></bp_sys_mean_comment><media_yn_comment></media_yn_comment><newdecimal_comment></newdecimal_comment><pain_level_comment></pain_level_comment><bp_ratio_lookup_comment></bp_ratio_lookup_comment><us_map_comment></us_map_comment><add_notes_comment></add_notes_comment><newselectitem_comment></newselectitem_comment><bp_dia_mean_comment></bp_dia_mean_comment><cascade3_comment></cascade3_comment><ecg_picture_comment></ecg_picture_comment><cascade2_comment></cascade2_comment><vas_question_comment></vas_question_comment></page2><meta><instanceID>uuid:1234</instanceID><instanceID_comment></instanceID_comment></meta></demo-vitals-grid-v6>

**Comment by MartijnR** [comment] 2018-09-20 21:52
No luck with reproducing this. It would be most efficient to run enketo in development mode like this:

```
grunt develop
```

If it is currently running with pm2, first do `pm2 stop enketo`.

Once it is running in development mode, the error message in the javascript console, should point to the line of code containing `.textContent`.

**Comment by MartijnR** [comment] 2018-09-24 18:52
logs are pointing to the repeat.js (core) call to obtain .repeat-number and get the textContent of this.

**Closed** 2018-09-24 22:03 UTC
