### ISSUE TITLE
CrossForm Logic retrieving incorrect data

### ISSUE THREAD

**Issue by kkrumlian** [OpenClinica/enketo-express-oc#729] opened 2023-12-05 16:36 UTC
The crossform logic for forms is retrieving the incorrect data when opening 2 forms concurrently. This occurs during the communication between SR and Enketo.

Open form for Participant 004Zique
![image-2023-12-05-10-49-14-193](https://github.com/OpenClinica/enketo-express-oc/assets/1571310/e5b5b199-50f6-4ca5-b976-ca9bcea24808)
Pretty concurrently open form for Participant 005Zique
![image-2023-12-05-10-49-02-095](https://github.com/OpenClinica/enketo-express-oc/assets/1571310/bce4b5e6-24f2-479e-b7c4-a57eb1a2f9ba)
Recognize the clinicadata.xml URLs in both screenshots. The URLs are identical but i think that's expected however the payload also seems to identical when concurrent loading happens. 
This screenshot shows the manifest being loaded for both requests 
![image-2023-12-05-10-57-15-429](https://github.com/OpenClinica/enketo-express-oc/assets/1571310/d37e4f53-ffed-4fe3-b7fc-c4ada92fa0c7)
Loading the clinicaldata links separately shows the correct ODM being sent to Enketo. 

![Screenshot from 2023-12-05 10-39-58](https://github.com/OpenClinica/enketo-express-oc/assets/1571310/a46c5fa3-a584-4830-8ac5-b4634b4aaf34)
![Screenshot from 2023-12-05 10-40-19](https://github.com/OpenClinica/enketo-express-oc/assets/1571310/0d61c157-a5f2-4654-88d9-7d71eb953473)

Can we discuss this in tomorrow's meeting.

**Comment by MartijnR** [comment] 2023-12-06 13:58
* [ ] try to reproduce
* [ ] is caching on the browser causing this? Does it load the file before it finds out the manifest hash changed?

**Comment by MartijnR** [comment] 2023-12-21 18:56
I've created a server mockup and now I can load the same form with a different ecid query parameter to get served a different external data file. I have not been able to reproduce a situation where I get served a different external XML file. I can show you live to see if this would correspond with the OC back end.

**Comment by kkrumlian** [comment] 2023-12-21 22:21
So @MartijnR looks like when Enketo calls OC again after the manifests call it calls the same clinicaldata URL twice: 
https://gist.github.com/iwoodferren/0686c05d403953b76895a5dbf535961f

**Comment by MartijnR** [comment] 2024-01-02 19:56
I added a question to the gist. 

I guess we can rule out any xml content caching cause on the Enketo side, but not much closer to figuring out the cause.

**Comment by kkrumlian** [comment] 2024-01-04 19:32
Here's an updated gist : https://gist.github.com/iwoodferren/d1ad948f4e3e465a74f5ae0342444c69
- We can see the calls for the manifests returning 2 different payloads with different ecids
- However when we check the requests coming from Enketo we see identical requests for a single ecid

**Comment by kkrumlian** [comment] 2024-01-04 19:32
@MartijnR ^^

**Comment by MartijnR** [comment] 2024-01-05 21:25
Thanks. I see something suspicious here: https://github.com/OpenClinica/enketo-express-oc/blob/master/app/lib/media.js#L302. 

It could be a caching issue on the Enketo side. However, if so, it is not yet clear why the external data is requested twice (instead of retrieved from the Enketo cache).

* [ ] The first step is to figure out how to reproduce this before attempting a fix. Try headless requests using '&'?

**Comment by MartijnR** [comment] 2024-01-05 21:34
**HOLD ON**❗❗❗    @kkrumlian the `<hash>` field is missing in the manifest published by OC! That would certainly be the most obvious culprit for caching issues.

When I mocked the OC backend to serve different external data files based on the `ecid` query parameter value I got these manifests (with a different hash value for houses.xml - ignore the second file):

<img width="973" alt="Screenshot 2024-01-05 at 4 33 11 PM" src="https://github.com/OpenClinica/enketo-express-oc/assets/627350/3d6d4fbd-767a-47f7-8a93-b57440992845">


<img width="986" alt="Screenshot 2024-01-05 at 4 33 14 PM" src="https://github.com/OpenClinica/enketo-express-oc/assets/627350/f75d67a1-81cf-4bc8-8521-2f26c2d21de9">

**Comment by pbowen-oc** [comment] 2024-01-12 14:10
Closing since this appears to be a non-Enketo issue

**Closed by pbowen-oc** 2024-01-12 14:10 UTC
