### ISSUE TITLE
Printed form includes History items corresponding to Irrelevant items

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#235] opened 2019-07-25 21:21 UTC
When we print a form containing data, irrelevant items are not included (as expected). However, the Query (comment) items accompanying them are being included in the printed view (not expected).

**Comment by MartijnR** [comment] 2019-07-25 21:26
Ah, I think, since query items are also 'just' questions, this may require adding the same relevant expression to those query items. Will check though.

**Comment by pbowen-oc** [comment] 2019-07-25 21:49
OK, thanks. In any case, we're not looking to pull this into our release next week.

**Comment by MartijnR** [comment] 2019-07-25 21:57
http://localhost:8005/single/fs/i/::8FaWL0oC (Centro)

**Comment by MartijnR** [comment] 2019-07-25 22:18
Yes, @pbowen-oc, I think that's the best solution. This makes using groups (logical groups without labels) with relevant expressions probably quite a bit more attractive than questions with individual relevant expressions.

**Comment by pbowen-oc** [comment] 2019-07-25 22:40
Would everything still work if we automatically set the comment item to have the same relevant logic as its linked question?

Either doing that or updating every item with relevant logic to be located within a group with that same relevant logic would seem to involve a lot of additional processing when a user uploads an XLS form, but I'd like to see what options we have for this.

**Comment by MartijnR** [comment] 2019-07-25 22:42
I believe all should still work if you'd do it like that but there will be a negative performance impact.

Actually, I'm just thinking of a possible alternative. Let me check.

**Comment by MartijnR** [comment] 2019-07-25 22:50
* [ ] look into NOT adding a printified class if linkedQuestion is disabled.

**Comment by MartijnR** [comment] 2019-07-26 20:34
Yep, found a very simple and, I think, robust solution, that only affects performance during print preparation.

**Comment by MartijnR** [comment] 2019-11-19 20:31
Only show history for disabled questions if the history is not empty.

**Comment by pbowen-oc** [comment] 2019-12-19 03:28
@MartijnR - I think we changed the scope of this to be different then what I had initially written, though it doesn't seem to be documented above.

What we're currently observing is that history is only included for items that are relevant (which aligns with the initial request above).

What we want now is is for history to be included for any item that has non-null history even if the item is not relevant.

AC1: When a form is printed only relevant items and items that have non-null values will be included in the printed version.
AC2: When a form is printed and Show History is not selected, history will not be included for any items.
AC3: When a form is printed and Show History is selected, history will be included for all items that have any history (values changes, query/annotation/RFC notes, etc.) even if those items are currently irrelevant and/or have null values.

We'd like this behavior to be in effect for on-form printing as well as the PDF endpoint.

**Comment by MartijnR** [comment] 2019-12-19 20:23
This is supposed to be done, according to the requirements in my last comment (which I believe is the same as what you just wrote). Will check!

**Comment by MartijnR** [comment] 2019-12-19 20:33
Yes, I can reproduce. Sorry about that!

**Comment by MartijnR** [comment] 2019-12-19 20:53
There is also a print-relevant-only setting to look into.

**Comment by MartijnR** [comment] 2019-12-19 23:40
I think I have a fix for this. By default non-relevant queries are displayed with an opacity. I was thinking maybe that is desirable, so left it for now.

**Closed** 2020-01-24 04:05 UTC
Labels: ready-for-final-review
